services:
  postgres:
    image: postgres:17
    ports:
      - "6724:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratelimit
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
